# Generated by Django 3.0.6 on 2020-07-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theft_app', '0004_cur1datamodel_cur2datamodel_sourcedatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cur1datamodel',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cur2datamodel',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sourcedatamodel',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
